######################################################################
#
# File name : dds_ip_tb.udo
# Created on: Wed Dec 25 10:43:52 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
