######################################################################
#
# File name : dds_ip_tb_wave.do
# Created on: Wed Dec 25 10:43:52 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
