######################################################################
#
# File name : dds_ip_tb_compile.do
# Created on: Thu Feb 27 19:17:36 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modeltech64_10.5\\win64\\vlib modelsim_lib/work
D:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim

D:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim/xbip_utils_v3_0_8
D:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim/axi_utils_v2_0_4
D:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim/xbip_pipe_v3_0_4
D:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim/xbip_bram18k_v3_0_4
D:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim/mult_gen_v12_0_13
D:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim/xbip_dsp48_wrapper_v3_0_4
D:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim/xbip_dsp48_addsub_v3_0_4
D:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim/xbip_dsp48_multadd_v3_0_4
D:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim/dds_compiler_v6_0_15
D:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_10.5\\win64\\vmap xbip_utils_v3_0_8 modelsim_lib/msim/xbip_utils_v3_0_8
D:\\modeltech64_10.5\\win64\\vmap axi_utils_v2_0_4 modelsim_lib/msim/axi_utils_v2_0_4
D:\\modeltech64_10.5\\win64\\vmap xbip_pipe_v3_0_4 modelsim_lib/msim/xbip_pipe_v3_0_4
D:\\modeltech64_10.5\\win64\\vmap xbip_bram18k_v3_0_4 modelsim_lib/msim/xbip_bram18k_v3_0_4
D:\\modeltech64_10.5\\win64\\vmap mult_gen_v12_0_13 modelsim_lib/msim/mult_gen_v12_0_13
D:\\modeltech64_10.5\\win64\\vmap xbip_dsp48_wrapper_v3_0_4 modelsim_lib/msim/xbip_dsp48_wrapper_v3_0_4
D:\\modeltech64_10.5\\win64\\vmap xbip_dsp48_addsub_v3_0_4 modelsim_lib/msim/xbip_dsp48_addsub_v3_0_4
D:\\modeltech64_10.5\\win64\\vmap xbip_dsp48_multadd_v3_0_4 modelsim_lib/msim/xbip_dsp48_multadd_v3_0_4
D:\\modeltech64_10.5\\win64\\vmap dds_compiler_v6_0_15 modelsim_lib/msim/dds_compiler_v6_0_15
D:\\modeltech64_10.5\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_10.5\\win64\\vcom -64 -93 -work xbip_utils_v3_0_8  \
"../../../../DDS.ip_user_files/ipstatic/hdl/xbip_utils_v3_0_vh_rfs.vhd" \

D:\\modeltech64_10.5\\win64\\vcom -64 -93 -work axi_utils_v2_0_4  \
"../../../../DDS.ip_user_files/ipstatic/hdl/axi_utils_v2_0_vh_rfs.vhd" \

D:\\modeltech64_10.5\\win64\\vcom -64 -93 -work xbip_pipe_v3_0_4  \
"../../../../DDS.ip_user_files/ipstatic/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \

D:\\modeltech64_10.5\\win64\\vcom -64 -93 -work xbip_bram18k_v3_0_4  \
"../../../../DDS.ip_user_files/ipstatic/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \

D:\\modeltech64_10.5\\win64\\vcom -64 -93 -work mult_gen_v12_0_13  \
"../../../../DDS.ip_user_files/ipstatic/hdl/mult_gen_v12_0_vh_rfs.vhd" \

D:\\modeltech64_10.5\\win64\\vcom -64 -93 -work xbip_dsp48_wrapper_v3_0_4  \
"../../../../DDS.ip_user_files/ipstatic/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \

D:\\modeltech64_10.5\\win64\\vcom -64 -93 -work xbip_dsp48_addsub_v3_0_4  \
"../../../../DDS.ip_user_files/ipstatic/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \

D:\\modeltech64_10.5\\win64\\vcom -64 -93 -work xbip_dsp48_multadd_v3_0_4  \
"../../../../DDS.ip_user_files/ipstatic/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \

D:\\modeltech64_10.5\\win64\\vcom -64 -93 -work dds_compiler_v6_0_15  \
"../../../../DDS.ip_user_files/ipstatic/hdl/dds_compiler_v6_0_vh_rfs.vhd" \

D:\\modeltech64_10.5\\win64\\vcom -64 -93 -work xil_defaultlib  \
"../../../../DDS.srcs/sources_1/ip/dds_compiler_1/sim/dds_compiler_1.vhd" \
"../../../../DDS.srcs/sources_1/ip/dds_compiler_0/sim/dds_compiler_0.vhd" \

D:\\modeltech64_10.5\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../DDS.srcs/sources_1/new/dds_test.v" \
"../../../../DDS.srcs/sim_1/new/dds_ip_tb.v" \

# compile glbl module
D:\\modeltech64_10.5\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

