# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath D:/modeltech64_10_5/win64
create_project -in_memory -part xc7z035ffg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/c_2019/dds_test/DDS/DDS.cache/wt [current_project]
set_property parent.project_path F:/c_2019/dds_test/DDS/DDS.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/c_2019/dds_test/DDS/DDS.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib F:/c_2019/dds_test/DDS/DDS.srcs/sources_1/new/dds_test.v
read_ip -quiet F:/c_2019/dds_test/DDS/DDS.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0.xci
set_property used_in_implementation false [get_files -all f:/c_2019/dds_test/DDS/DDS.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0_ooc.xdc]

read_ip -quiet F:/c_2019/dds_test/DDS/DDS.srcs/sources_1/ip/dds_compiler_1/dds_compiler_1.xci
set_property used_in_implementation false [get_files -all f:/c_2019/dds_test/DDS/DDS.srcs/sources_1/ip/dds_compiler_1/dds_compiler_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top dds_test -part xc7z035ffg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef dds_test.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file dds_test_utilization_synth.rpt -pb dds_test_utilization_synth.pb"
